name: FancyPerks
description: $description
author: OliverHD, DatLicht, FemBoysAreCut3
version: ${project.version}
folia-supported: true
main: de.oliver.fancyperks.FancyPerks
api-version: 1.21
loadbefore:
  - Vault
  - Essentials
  - LuckPerms
commands:
  FancyPerks:
    permission: FancyPerks.admin
  Perks:
    aliases:
      - perk